In [1]:
import pandas as pd

In [2]:
url = "https://en.wikipedia.org/wiki/World_Happiness_Report#2016_World_Happiness_Report"

In [3]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[37] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                  NaN             NaN
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                         NaN        NaN              NaN             NaN
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2               NaN                      NaN                           NaN
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2           NaN         NaN         NaN
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0            NaN            NaN                       NaN    NaN
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...
 152          151              1                    Rwanda  3.471
 153          152              4                     Syria  3.462
 154          153              4                  Tanzania  3.349
 155          154              3                   Burundi  2.905
 156          155            NaN  Central African Republic  2.693

      Change in score  GDP per capita  Social support  Healthy life expectancy  \
 0                NaN             NaN             NaN                      NaN
 1              0.004           1.482           1.551                    0.793
 2              0.003           1.481           1.611                    0.834
 3              0.015           1.565           1.517                    0.858
 4              0.056           1.444           1.540                    0.809
 ..               ...             ...             ...                      ...
 152            0.044           0.369           0.946                    0.326
 153            0.393           0.777           0.396                    0.501
 154            0.317           0.511           1.042                    0.365
 155              NaN           0.092           0.630                    0.152
 156              NaN           0.000           0.000                    0.019

      Freedom to make life choices  Generosity  Trust  Residual
 0                             NaN         NaN    NaN       NaN
 1                           0.626       0.355  0.401     2.314
 2                           0.627       0.476  0.154     2.323
 3                           0.620       0.291  0.367     2.277
 4                           0.618       0.245  0.383     2.430
 ..                            ...         ...    ...       ...
 152                         0.582       0.253  0.455     0.540
 153                         0.082       0.494  0.151     1.062
 154                         0.390       0.354  0.066     0.621
 155                         0.060       0.204  0.084     1.683
 156                         0.271       0.281  0.057     2.066

 [157 rows x 12 columns],
                                                  Table  \
 0    Legend:[38] .mw-parser-output .legend{page-bre...
 1    .mw-parser-output .legend{page-break-inside:av...
 2                                 Overall Rank[40][41]
 3                                                    1
 4                                                    2
 ..                                                 ...
 155                                                153
 156                                                154
 157                                                155
 158                                                156
 159                                                157

                                             Unnamed: 1 Unnamed: 2  \
 0                                                  NaN        NaN
 1    Explained by: Freedom to make life choices  Ex...        NaN
 2                                              Country      Score
 3                                              Denmark      7.526
 4                                          Switzerland      7.509
 ..                                                 ...        ...
 155                                              Benin      3.484
 156                                        Afghanistan      3.360
 157                                               Togo      3.303
 158                                              Syria      3.069
 159                                            Burundi      2.905

                 Unnamed: 3      Unnamed: 4      Unnamed: 5  \
 0                      NaN             NaN             NaN
 1                      NaN             NaN             NaN
 2    Change OverPrior Year  GDP per capita  Social support
 3                   -0.401             NaN             NaN
 4                    0.035             NaN             NaN
 ..                     ...             ...             ...
 155                  0.154             NaN             NaN
 156                  0.000             NaN             NaN
 157                  0.100             NaN             NaN
 158                  0.000             NaN             NaN
 159                  0.000             NaN             NaN

                   Unnamed: 6                    Unnamed: 7  Unnamed: 8  \
 0                        NaN                           NaN         NaN
 1                        NaN                           NaN         NaN
 2    Healthy life expectancy  Freedom to make life choices  Generosity
 3                        NaN                           NaN         NaN
 4                        NaN                           NaN         NaN
 ..                       ...                           ...         ...
 155                      NaN                           NaN         NaN
 156                      NaN                           NaN         NaN
 157                      NaN                           NaN         NaN
 158                      NaN                           NaN         NaN
 159                      NaN                           NaN         NaN

     Unnamed: 9
 0          NaN
 1          NaN
 2        Trust
 3          NaN
 4          NaN
 ..         ...
 155        NaN
 156        NaN
 157        NaN
 158        NaN
 159        NaN

 [160 rows x 10 columns],
                                                    0  \
 0  .mw-parser-output .legend{page-break-inside:av...

                                                    1
 0  Explained by: Freedom to make life choices  Ex...  ,
      Overall Rank[40][41]      Country  Score  Change OverPrior Year  \
 0                       1      Denmark  7.526                 -0.401
 1                       2  Switzerland  7.509                  0.035
 2                       3      Iceland  7.501                  0.000
 3                       4       Norway  7.498                  0.082
 4                       5      Finland  7.413                 -0.259
 ..                    ...          ...    ...                    ...
 152                   153        Benin  3.484                  0.154
 153                   154  Afghanistan  3.360                  0.000
 154                   155         Togo  3.303                  0.100
 155                   156        Syria  3.069                  0.000
 156                   157      Burundi  2.905                  0.000

      GDP per capita  Social support  Healthy life expectancy  \
 0               NaN             NaN                      NaN
 1               NaN             NaN                      NaN
 2               NaN             NaN                      NaN
 3               NaN             NaN                      NaN
 4               NaN             NaN                      NaN
 ..              ...             ...                      ...
 152             NaN             NaN                      NaN
 153             NaN             NaN                      NaN
 154             NaN             NaN                      NaN
 155             NaN             NaN                      NaN
 156             NaN             NaN                      NaN

      Freedom to make life choices  Generosity  Trust
 0                             NaN         NaN    NaN
 1                             NaN         NaN    NaN
 2                             NaN         NaN    NaN
 3                             NaN         NaN    NaN
 4                             NaN         NaN    NaN
 ..                            ...         ...    ...
 152                           NaN         NaN    NaN
 153                           NaN         NaN    NaN
 154                           NaN         NaN    NaN
 155                           NaN         NaN    NaN
 156                           NaN         NaN    NaN

 [157 rows x 10 columns],
    vteLists of countries by quality of life rankings  \
 0                                            General
 1                                           Economic
 2                                        Environment
 3                                             Health
 4                                   Social/Political
 5  List of international rankings List of top int...

   vteLists of countries by quality of life rankings.1
 0  Life expectancy Europe South America World Hap...
 1  Net take-home pay Long-term unemployment rate ...
 2  Greenhouse gas emissions per capita Dashboard ...

In [9]:
tables[4]

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091